{
 "title": "MySQL Server Dash Board",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Queries Rate",
   "type": "graph",
   "description": "Count of All Queries run (select, insert, update, etc,)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_queries[1m])",
     "legendFormat": "Queries Per Minute"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "mysql_global_status_max_used_connections",
     "legendFormat": "Max Used Connections"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "description": "Display Current Active connections",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 7 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Active Connections"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "singlestat",
   "description": "Display Maximum Connections",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections",
     "legendFormat": "Active Connections"
    }
   ]
  }
 ]
}